[tool.poetry]
name = "dbt-loom"
version = "0.3.1"
description = "A dbt-core plugin to import public nodes in multi-project deployments."
authors = ["Nicholas Yager <yager@nicholasyager.com>"]
readme = "README.md"
packages = [{ include = "dbt_loom" }]

[tool.commitizen]
version = "0.3.1"
version_files = ["pyproject.toml:^version"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
dbt-core = ">=1.6.0,<1.8.0"
requests = "^2.31.0"
google-cloud-storage = "^2.14.0"
boto3 = "^1.34.14"
azure-storage-blob = "^12.19.0"
azure-identity = "^1.15.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.278"
pytest = "^7.4.0"
isort = "^5.12.0"
black = "^23.7.0"
dbt-duckdb = "^1.6.0"
duckdb = ">=0.8.0"
pre-commit = "^3.6.0"
mypy = "^1.8.0"

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
